version: "3.9"

services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

#  redis:
 #   image: redis:6.2-alpine
  #  restart: always
   # env_file:
    #  - ./.env
#    ports:
 #     - ${REDIS_PORT}:6379
  #  command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
   # volumes:
    #  - redis-data:/data

  main:
    depends_on:
      - db

    container_name: mainService
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    volumes:
      - ./config/config.yaml:/usr/local/src/config/config.yaml

volumes:
  postgresdb-data:
    driver: local
  redis-data:
    driver: local
